version: '3.4'

services:
  catalogdb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  cache:
    image: redis:latest
    restart: always
    ports:
        - '6379:6379'

  fh.catalogservice.api:
    image: ${DOCKER_REGISTRY-}fhcatalogserviceapi
    build:
      context: .
      dockerfile: src/FH.CatalogService.API/Dockerfile
    depends_on:
        - catalogdb
        - cache