version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    environment:
        SA_PASSWORD: "yl!@AfZAjA95"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"


  fh.catalogservice.api:
    container_name: catalogServiceApi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"
    depends_on:
        - catalogdb